### ISSUE TITLE
Gzip already returns a Buffer

### ISSUE THREAD

**Issue by avranju** [Azure/iot-gateway-compression-gzip-nodejs#2]
### Description

In https://github.com/Azure/iot-gateway-compression-gzip-nodejs/blob/master/compressor.js#L22, do we need to convert the buffer to a base 64 string first and then again back to a buffer before converting it into an `Uint8Array`?

**Comment by WilliamBerryiii** [comment]
I had initially done that to allow for the compressed data length to be inserted at the front of the buffer, but as that's been removed there is likely little gain.  I could see pulling out the base64 string and leveraging a debug output for when and if the gateway supports that type of feature.  I think for now it's safe to remove and tighten the code up.  Thanks for the issue!
